data:
  min_frequency: 3
  stopword_path: ./text_data/stopwords.txt
  positive_path: ./text_data/comments_positive.txt
  negative_path: ./text_data/comments_negative.txt
  vocab_path: ./text_data/vocab.pkl
  train_path: ./text_data/train.pkl
  test_path: ./text_data/test.pkl
  seg_path: ./text_data/seg.txt

model:
  batch_size: 128
  train_epochs: 5
  embedding_path: ./embedding.txt
  data_dir: ./text_data
  fix_embedding: true
  embedding_size: 128
  num_layers: 2
  seq_length: 50
  rnn_size: 128
  label_size: 2
  learning_rate: 0.005
  use_word2vec: true
  use_bilstm: false
  summary_path: ./logs/summary
  ckpt_path: ./ckpt
  pb_path: ./tfserving
  display_train: 10
  display_test: 100
